# Generated by Django 3.2 on 2021-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('tweet', models.TextField(max_length=280)),
                ('prediction_value', models.FloatField()),
                ('prediction_date', models.DateTimeField()),
                ('tweet_created_date', models.DateTimeField()),
            ],
        ),
    ]
