# Generated by Django 3.2 on 2021-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.TextField(max_length=280),
        ),
    ]
