# Generated by Django 3.2 on 2021-05-10 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('prediction1', models.FloatField()),
                ('q2', models.TextField()),
                ('prediction2', models.FloatField()),
                ('mean', models.FloatField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anwser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
