# Generated by Django 3.2 on 2021-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_twitteruser_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='tweet_created_date',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='prediction_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
