name: API test

on:
  push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
          TWITTER_CONSUMER_KEY: HEYyPEXGQsfBVLKK6hI2SfFdr
          TWITTER_CONSUMER_SECRET: xsoBXVl1WY2RBIsirbxgLQgvri9E9gG9iHfiUUB7HNAv4gRJhc
          TWITTER_ACCESS_TOKEN: 1015944194966208512-0XLPaLKQRhtAZUHEPn9ZRLeRB2jAR4
          TWITTER_ACCESS_TOKEN_SECRET: sJsJaQDbfje2lv8hUcPbdkfZnWrmY6a4zouaf9JzWtF04
          DJANGO_SECRET: wxv4i+6#1ckg_vg__q&jd1rsn*#ofsdxazzld5gfb013(^la-o
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ls -la
        cd data
        ls -la
        cd .. && cd api
        ls -la
        cd ..
        ls
        python manage.py migrate
    - name: Lint with flake8
      env:
          TWITTER_CONSUMER_KEY: HEYyPEXGQsfBVLKK6hI2SfFdr
          TWITTER_CONSUMER_SECRET: xsoBXVl1WY2RBIsirbxgLQgvri9E9gG9iHfiUUB7HNAv4gRJhc
          TWITTER_ACCESS_TOKEN: 1015944194966208512-0XLPaLKQRhtAZUHEPn9ZRLeRB2jAR4
          TWITTER_ACCESS_TOKEN_SECRET: sJsJaQDbfje2lv8hUcPbdkfZnWrmY6a4zouaf9JzWtF04
          DJANGO_SECRET: wxv4i+6#1ckg_vg__q&jd1rsn*#ofsdxazzld5gfb013(^la-o
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unittests
      env:
          TWITTER_CONSUMER_KEY: HEYyPEXGQsfBVLKK6hI2SfFdr
          TWITTER_CONSUMER_SECRET: xsoBXVl1WY2RBIsirbxgLQgvri9E9gG9iHfiUUB7HNAv4gRJhc
          TWITTER_ACCESS_TOKEN: 1015944194966208512-0XLPaLKQRhtAZUHEPn9ZRLeRB2jAR4
          TWITTER_ACCESS_TOKEN_SECRET: sJsJaQDbfje2lv8hUcPbdkfZnWrmY6a4zouaf9JzWtF04
          DJANGO_SECRET: wxv4i+6#1ckg_vg__q&jd1rsn*#ofsdxazzld5gfb013(^la-o
      run: |
        python manage.py test